// Fictional sample stories so the UI has content before the first RSS refresh.
// Teams and people are invented on purpose — do not replace with real-sounding "facts".
const img = (seed: string) => `https://picsum.photos/seed/haystack-${seed}/1200/800`;

export const SAMPLE_ARTICLES = [
  {
    sport: "soccer",
    title: "Stoppage-time header keeps Riverside in the title race",
    summary: "A 94th-minute equalizer at the Harbour Ground leaves the top three separated by two points with six matches left.",
    body: "Riverside looked beaten until a corner in the fourth minute of added time found captain Tomas Brandt unmarked at the back post.\n\nThe draw ends the hosts' seven-match winning run and keeps the championship race open heading into the final stretch. \"We never stop,\" Brandt said. \"Six finals now.\"\n\nRiverside travel to the league leaders next weekend.",
    source: "Haystack Sample Wire",
    imageUrl: img("soccer-1"),
    url: "https://example.com/sample/soccer-stoppage-time-header",
  },
  {
    sport: "soccer",
    title: "Teenage midfielder signs first professional contract",
    summary: "The 17-year-old academy graduate has been handed a three-year deal after a breakout preseason.",
    body: "Northgate have tied down academy midfielder Leo Marsh on a three-year professional contract.\n\nMarsh started four of the club's five preseason friendlies and impressed coaches with his range of passing. The club expects him to feature in cup competitions this season.",
    source: "Haystack Sample Wire",
    imageUrl: img("soccer-2"),
    url: "https://example.com/sample/soccer-teen-midfielder-contract",
  },
  {
    sport: "nba",
    title: "Comets rally from 22 down behind 41-point night",
    summary: "A fourth-quarter surge completes the season's biggest comeback and snaps a three-game skid.",
    body: "Trailing by 22 early in the third quarter, the Comets outscored their visitors 38-17 in the fourth behind guard Andre Wells, who finished with 41 points and nine assists.\n\n\"We just got stops,\" Wells said. \"Everything on offense came from defense.\"\n\nThe Comets host a back-to-back starting Friday.",
    source: "Haystack Sample Wire",
    imageUrl: img("nba-1"),
    url: "https://example.com/sample/nba-comets-comeback",
  },
  {
    sport: "nba",
    title: "Rookie center posts first career triple-double",
    summary: "Twelve points, eleven rebounds and ten blocks in only his ninth professional game.",
    body: "Rookie center Malik Osei recorded the rare blocks triple-double in a 108-96 win, the first by a first-year player in franchise history.\n\nOsei's coach called it \"the kind of night you build a defense around.\"",
    source: "Haystack Sample Wire",
    imageUrl: img("nba-2"),
    url: "https://example.com/sample/nba-rookie-triple-double",
  },
  {
    sport: "nfl",
    title: "Backup quarterback leads game-winning drive in debut",
    summary: "Pressed into action in the second quarter, the third-year passer goes 8-for-9 on the final possession.",
    body: "With the starter sidelined by an ankle injury, backup Jordan Pike engineered a 75-yard drive in the final two minutes, capped by a 12-yard touchdown pass with 0:14 on the clock.\n\nThe team says the starter's injury will be evaluated this week.",
    source: "Haystack Sample Wire",
    imageUrl: img("nfl-1"),
    url: "https://example.com/sample/nfl-backup-qb-debut",
  },
  {
    sport: "nfl",
    title: "Defense forces five turnovers in division shutout",
    summary: "Three interceptions and two fumble recoveries deliver the first shutout of the season.",
    body: "The Ironclads defense dominated from the opening drive, forcing five turnovers in a 27-0 division win.\n\nSafety Chris Okafor had two of the interceptions and returned one 64 yards for a touchdown.",
    source: "Haystack Sample Wire",
    imageUrl: img("nfl-2"),
    url: "https://example.com/sample/nfl-five-turnover-shutout",
  },
  {
    sport: "f1",
    title: "Wet-weather gamble hands pole to the midfield",
    summary: "A late switch to intermediates puts an unexpected name at the front of the grid.",
    body: "As rain arrived in the final minutes of qualifying, one midfield team switched to intermediate tyres a lap earlier than everyone else — and it paid off with pole position.\n\nThe championship leaders start from the third row after mistiming their own call.",
    source: "Haystack Sample Wire",
    imageUrl: img("f1-1"),
    url: "https://example.com/sample/f1-wet-weather-pole",
  },
  {
    sport: "f1",
    title: "Two-stop strategy decides a tense street-circuit race",
    summary: "An undercut on lap 41 settles a race that was won and lost in the pit lane.",
    body: "A second pit stop that looked like a mistake turned into the winning move as fresh tyres delivered lap times a full second quicker than the leaders.\n\nThe result tightens the constructors' standings with five rounds remaining.",
    source: "Haystack Sample Wire",
    imageUrl: img("f1-2"),
    url: "https://example.com/sample/f1-two-stop-strategy",
  },
  {
    sport: "tennis",
    title: "Qualifier stuns top seed in three-set thriller",
    summary: "Ranked outside the top 100, the 20-year-old saves four match points to reach the quarterfinals.",
    body: "Qualifier Elena Varga saved four match points in the deciding set before winning a final-set tiebreak 10-8 against the tournament's top seed.\n\n\"I just tried to stay in every point,\" she said. Varga plays another qualifier for a place in the semifinals.",
    source: "Haystack Sample Wire",
    imageUrl: img("tennis-1"),
    url: "https://example.com/sample/tennis-qualifier-upset",
  },
  {
    sport: "tennis",
    title: "Veteran announces this season will be the last",
    summary: "The 36-year-old two-time finalist plans a farewell tour through the autumn swing.",
    body: "In an emotional press conference, veteran Marco Ruiz confirmed he will retire at the end of the season after 18 years on tour.\n\nRuiz said he wants to finish \"on a court, not in a doctor's office.\"",
    source: "Haystack Sample Wire",
    imageUrl: img("tennis-2"),
    url: "https://example.com/sample/tennis-veteran-retirement",
  },
  {
    sport: "nhl",
    title: "Overtime winner caps four-goal third-period comeback",
    summary: "Down 4-0 after forty minutes, the Glaciers score five unanswered.",
    body: "The Glaciers erased a four-goal deficit in the third period and won it 2:13 into overtime on a wrist shot from defenseman Nils Aho.\n\nIt is the largest comeback in the league this season.",
    source: "Haystack Sample Wire",
    imageUrl: img("nhl-1"),
    url: "https://example.com/sample/nhl-overtime-comeback",
  },
  {
    sport: "nhl",
    title: "Goaltender records 50-save shutout",
    summary: "A career night in net steals two points on the road.",
    body: "Goaltender Sam Lindqvist stopped all 50 shots he faced in a 1-0 road win, including 21 in the third period.\n\nHis teammates mobbed him at the final buzzer. \"He won us that game alone,\" his captain said.",
    source: "Haystack Sample Wire",
    imageUrl: img("nhl-2"),
    url: "https://example.com/sample/nhl-50-save-shutout",
  },
];
